
# Settings used for the server link
server:

  # Name of the server
  # Use what's normally allowed in Minecraft names for this (Regex: '[a-zA-Z0-9_]{1,16}')
  name: "world1"

  # TODO Add arrival particle effect (plays at the player when they arrive)
  # TODO Add arrival commands (same concept as above)

  # Database settings used for.... a database?
  database:
    host: "127.0.0.1"
    port: "3306"
    database: "default"
    username: "admin"
    password: ""

  # Settings used for the server selector
  selector:

    # List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    material: "STICK"

    # Does the item have to match the data listed below?
    exact_match: false

    # Data value of the selector item
    data: 0

    # Display name of the item (allows color codes)
    display_name: "World Selector"

    # Lore of the item (also allows for color codes)
    lore:
      - "Selector of worlds!"

# Other worlds that players can travel to from this world
links:

  # Name of the world the player can teleport to
  name_of_other_world:

    # Triggers used for unlocking the world
    triggers:

      # Advancement trigger used to unlock world
      # The link will be unlocked and added to the player once this advancement is completed
      advancement: "name_space:with/name_here"

    # Displays the link in the menu only if these conditions are met
    display_conditions:

      # Advancements required to see the link
      # This can be left untouched if you want it to display all the time or if nothing is required
      advancements:
        - "name_space:with/name_here"

      # Location required to see the link
      # Coordinates can be left as '~' if you don't care what location it is
      location: "~, ~, ~"

      # TODO Add more customization for this option
      # Offhand item required to see the link
      offhand_item: ""

      # TODO
      on_material: ""

      # TODO 5-10 or >5 or =7
      health: ""

      # TODO like health
      hunger: ""

      # TODO day, night, int_values, etc.
      time: ""

    # Effects of the world particle
    effects:

      # Zoom in on click (adds slowness)
      zoom: true

      # Blindness on click
      blindness: true

      # TODO Play portal sound on click
      sound: true

      # -----
      # Add further customization with "before" commands if you want to add other stuff on click (located under teleportation)
      # -----

      # Particles that will show for the world particle
      particles:

        # The particle that will display when holding the selection tool
        # List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
        display:

          type: "FLAME"
          offset: "0.0, 0.0, 0.0"
          speed: 0
          count: 1

        # The particle that will display when hovering over the world particle
        hover:

          type: "PORTAL"
          offset: "0.0, 0.0, 0.0"
          speed: 0
          count: 1

    # Events that will take place when teleporting to the other world
    teleportation:

      # The type of teleportation that will take place
      #

      # ABSOLUTE
      # - This will always teleport you to the coordinates and world provided
      #
      # RELATIVE
      # - This acts like a '~' in the /tp command where it takes your current coordinates and adds to them
      #
      #
      # Note: If you append `_SAFE` to the end of any type, it will always put you in a safe place
      #
      type: "RELATIVE_SAFE"

      # The location in the other world
      location:

        # If a value is not set, the server will use the current player location value.
        # Example: If y is not set, the location will use x, z, yaw and pitch from the config, and use the player's y value.
        world: "world"
        x: 100.0
        y: 62.0
        z: -100.0
        yaw: 0
        pitch: 0

      # Commands run when the teleportation takes place
      #
      # %player% = player's name
      # %world% = the world's name they are teleporting to
      #
      # Commands also accept color codes (&7 = gray)
      commands:

        before:
          - "say Sending %player% to %world%"

        during:
          - "say %player% is about to go bye bye!"

        # Note: Do not execute off player as they have already left the server
        after:
          - "say %player% has gone to %world% :("


