name: WorldLink
version: ${project.version}
main: co.gm4.worldlink.WorldLink
authors: [MatrixTunnel, theminecoder]

commands:
  wlabout:
    description: Shows license and source code
    permission: gm4.command.about
    usage: /wlabout
  world:
    description: Allows you to connect to the different worlds
    permission: gm4.command.world
    usage: /world <name>
  wlreload:
    description: Reloads the config of WorldLink
    permission: gm4.command.reload
    usage: /wlreload

permissions:
  gm4.command.wlabout:
    default: true
  gm4.command.world:
    default: op
  gm4.command.reload:
    default: op
